version: "3"
services:
  webapp:
    build: .
    restart: always
    ports: 
      - 8080:8080
    depends_on:
      -mysqldb
      
  mysqldb:
    image: "mysql:5.6"
    restart: always
    ports:
      - 3306:3306      
    MYSQL_DATABASE: fitness  
    MYSQL_USER: root
    MYSQL_PASSWORD: admin789
    MYSQL_ROOT_PASSWORD: admin789
    volumes: 
      - data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      
volumes:
  data: {}      
    
